# Frontend build and deployment configuration
[build]
builder = "NIXPACKS"
buildCommand = "npm run build -- --configuration=production"

[deploy]
# Use the Angular build output directory with browser subdirectory
startCommand = "npx serve -s dist/frontend/browser"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckEnabled = true

# Environment variables for API connectivity
[variables]
API_URL = "${{ backend.RAILWAY_PUBLIC_DOMAIN }}"
NODE_ENV = "production"
